### ISSUE TITLE
Links for latest completed versions of web standards are not consistent

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-intro-linking#2]
In Referencing Guidelines and Other Technical Specifications,  Accessible Rich Internet Applications (WAI-ARIA) http://www.w3.org/TR/wai-aria/ does not link to the current version as specified.

This section should be re-written depending on whether the WAI-ARIA link is changed to work as the other specifications do.

**Comment by lakeen** [comment]
Also as other technical specifications do, should http://www.w3.org/TR/wai-aria10/ work?

**Comment by yatil** [comment]
I _think_ http://www.w3.org/TR/wai-aria/ will link to [ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/) once it comes out of Candidate Recommendation and becomes a Recommendation. I think wai-aria10 or wai-aria-1.0 (to have the same format as 1.1 above) should indeed work.

Maybe @michael-n-cooper can quickly comment if I got that right?

**Comment by michael-n-cooper** [comment]
On 19/10/2017 8:11 AM, Eric Eggert wrote:
>
> I /think/ http://www.w3.org/TR/wai-aria/ will link to ARIA 1.1 
> <https://www.w3.org/TR/wai-aria-1.1/> once it comes out of Candidate 
> Recommendation and becomes a Recommendation. I think wai-aria10 or 
> wai-aria-1.0 (to have the same format as 1.1 above) should indeed work.
>
Probably. I don't have a formal decision to do that, and there isn't a 
clear path to make it happen besides "ask Denis", but I think it's the 
general expectation.

Probably at the same time we would introduce wai-aria-1.0 to reference 
the 1.0 version. We shouldda done that from the start, but the 
versioning guidance at https://www.w3.org/2005/05/tr-versions isn't 
anywhere near clear enough to know what to do when starting a new spec.

**Comment by michael-n-cooper** [comment]
wai-aria now loads the latest ARIA specifications, and wai-aria-1.0 and wai-aria-1.1 load appropriate versions respectively.

**Comment by yatil** [comment]
Thanks, @michael-n-cooper!
